//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GX26Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GX26Bot.Resources.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso2_2a.png.
        /// </summary>
        internal static string BallroomA {
            get {
                return ResourceManager.GetString("BallroomA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso2_2b.png.
        /// </summary>
        internal static string BallroomB {
            get {
                return ResourceManager.GetString("BallroomB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso2_2c.png.
        /// </summary>
        internal static string BallroomC {
            get {
                return ResourceManager.GetString("BallroomC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso2_ba.png.
        /// </summary>
        internal static string Bathroom2 {
            get {
                return ResourceManager.GetString("Bathroom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso3_ba.png.
        /// </summary>
        internal static string Bathroom3 {
            get {
                return ResourceManager.GetString("Bathroom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso4_ba_sin_ref.png.
        /// </summary>
        internal static string Bathroom4 {
            get {
                return ResourceManager.GetString("Bathroom4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso2_rop.png.
        /// </summary>
        internal static string CoatCheck {
            get {
                return ResourceManager.GetString("CoatCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso4_4C.png.
        /// </summary>
        internal static string ConferenceRoom {
            get {
                return ResourceManager.GetString("ConferenceRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso3_3F.png.
        /// </summary>
        internal static string Florida {
            get {
                return ResourceManager.GetString("Florida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://upload.wikimedia.org/wikipedia/commons/5/56/Answer_to_Life.png.
        /// </summary>
        internal static string FortyTwo {
            get {
                return ResourceManager.GetString("FortyTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso2_2GB.png.
        /// </summary>
        internal static string GrandBallroom {
            get {
                return ResourceManager.GetString("GrandBallroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://images.travelpod.com/cache/accom_maps/Radisson_Victoria_Plaza-Montevideo.gif.
        /// </summary>
        internal static string GX26 {
            get {
                return ResourceManager.GetString("GX26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PenarolNacional.png.
        /// </summary>
        internal static string Penarol {
            get {
                return ResourceManager.GetString("Penarol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso4_4P.png.
        /// </summary>
        internal static string Picasso {
            get {
                return ResourceManager.GetString("Picasso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa_GX26_piso4_4R.png.
        /// </summary>
        internal static string Renoir {
            get {
                return ResourceManager.GetString("Renoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vader.jpg.
        /// </summary>
        internal static string Vader {
            get {
                return ResourceManager.GetString("Vader", resourceCulture);
            }
        }
    }
}
