//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GX26Bot.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SourceParam", Namespace="http://www.gxtechnical.com/")]
    [System.SerializableAttribute()]
    public partial class SourceParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sourceNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sourceName {
            get {
                return this.sourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceNameField, value) != true)) {
                    this.sourceNameField = value;
                    this.RaisePropertyChanged("sourceName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://www.gxtechnical.com/")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GX26Bot.ServiceReference.DocumentProperty[] PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public GX26Bot.ServiceReference.DocumentProperty[] Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentProperty", Namespace="http://www.gxtechnical.com/")]
    [System.SerializableAttribute()]
    public partial class DocumentProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        private float BoostField;
        
        private bool SearchableField;
        
        private bool RedundantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float Boost {
            get {
                return this.BoostField;
            }
            set {
                if ((this.BoostField.Equals(value) != true)) {
                    this.BoostField = value;
                    this.RaisePropertyChanged("Boost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Searchable {
            get {
                return this.SearchableField;
            }
            set {
                if ((this.SearchableField.Equals(value) != true)) {
                    this.SearchableField = value;
                    this.RaisePropertyChanged("Searchable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Redundant {
            get {
                return this.RedundantField;
            }
            set {
                if ((this.RedundantField.Equals(value) != true)) {
                    this.RedundantField = value;
                    this.RaisePropertyChanged("Redundant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResult", Namespace="http://www.gxtechnical.com/")]
    [System.SerializableAttribute()]
    public partial class SearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DocumentsCountField;
        
        private int TotalPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GX26Bot.ServiceReference.Document[] DocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DocumentsCount {
            get {
                return this.DocumentsCountField;
            }
            set {
                if ((this.DocumentsCountField.Equals(value) != true)) {
                    this.DocumentsCountField = value;
                    this.RaisePropertyChanged("DocumentsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public GX26Bot.ServiceReference.Document[] Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SearchTime {
            get {
                return this.SearchTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchTimeField, value) != true)) {
                    this.SearchTimeField = value;
                    this.RaisePropertyChanged("SearchTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchParameter", Namespace="http://www.gxtechnical.com/")]
    [System.SerializableAttribute()]
    public partial class SearchParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GX26Bot.ServiceReference.SourceParam[] SourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GX26Bot.ServiceReference.SearchProperty[] SearchPropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchText {
            get {
                return this.SearchTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchTextField, value) != true)) {
                    this.SearchTextField = value;
                    this.RaisePropertyChanged("SearchText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GX26Bot.ServiceReference.SourceParam[] Sources {
            get {
                return this.SourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.SourcesField, value) != true)) {
                    this.SourcesField = value;
                    this.RaisePropertyChanged("Sources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public GX26Bot.ServiceReference.SearchProperty[] SearchProperties {
            get {
                return this.SearchPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchPropertiesField, value) != true)) {
                    this.SearchPropertiesField = value;
                    this.RaisePropertyChanged("SearchProperties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchProperty", Namespace="http://www.gxtechnical.com/")]
    [System.SerializableAttribute()]
    public partial class SearchProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gxtechnical.com/", ConfigurationName="ServiceReference.SearchServiceSoap")]
    public interface SearchServiceSoap {
        
        // CODEGEN: Generating message contract since element name text from namespace http://www.gxtechnical.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gxtechnical.com/Search", ReplyAction="*")]
        GX26Bot.ServiceReference.SearchResponse Search(GX26Bot.ServiceReference.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gxtechnical.com/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<GX26Bot.ServiceReference.SearchResponse> SearchAsync(GX26Bot.ServiceReference.SearchRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://www.gxtechnical.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gxtechnical.com/Search2", ReplyAction="*")]
        GX26Bot.ServiceReference.Search2Response Search2(GX26Bot.ServiceReference.Search2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gxtechnical.com/Search2", ReplyAction="*")]
        System.Threading.Tasks.Task<GX26Bot.ServiceReference.Search2Response> Search2Async(GX26Bot.ServiceReference.Search2Request request);
        
        // CODEGEN: Generating message contract since element name searchParameter from namespace http://www.gxtechnical.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gxtechnical.com/Search3", ReplyAction="*")]
        GX26Bot.ServiceReference.Search3Response Search3(GX26Bot.ServiceReference.Search3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gxtechnical.com/Search3", ReplyAction="*")]
        System.Threading.Tasks.Task<GX26Bot.ServiceReference.Search3Response> Search3Async(GX26Bot.ServiceReference.Search3Request request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://www.gxtechnical.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gxtechnical.com/SearchPrivate", ReplyAction="*")]
        GX26Bot.ServiceReference.SearchPrivateResponse SearchPrivate(GX26Bot.ServiceReference.SearchPrivateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gxtechnical.com/SearchPrivate", ReplyAction="*")]
        System.Threading.Tasks.Task<GX26Bot.ServiceReference.SearchPrivateResponse> SearchPrivateAsync(GX26Bot.ServiceReference.SearchPrivateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://www.gxtechnical.com/", Order=0)]
        public GX26Bot.ServiceReference.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(GX26Bot.ServiceReference.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gxtechnical.com/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GX26Bot.ServiceReference.SourceParam[] sources;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cssClassForHighlight;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(string text, GX26Bot.ServiceReference.SourceParam[] sources, string cssClassForHighlight) {
            this.text = text;
            this.sources = sources;
            this.cssClassForHighlight = cssClassForHighlight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://www.gxtechnical.com/", Order=0)]
        public GX26Bot.ServiceReference.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(GX26Bot.ServiceReference.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gxtechnical.com/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GX26Bot.ServiceReference.Document[] SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(GX26Bot.ServiceReference.Document[] SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Search2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search2", Namespace="http://www.gxtechnical.com/", Order=0)]
        public GX26Bot.ServiceReference.Search2RequestBody Body;
        
        public Search2Request() {
        }
        
        public Search2Request(GX26Bot.ServiceReference.Search2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gxtechnical.com/")]
    public partial class Search2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GX26Bot.ServiceReference.SourceParam[] sources;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cssClassForHighlight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pageSize;
        
        public Search2RequestBody() {
        }
        
        public Search2RequestBody(string text, GX26Bot.ServiceReference.SourceParam[] sources, string cssClassForHighlight, int pageNumber, int pageSize) {
            this.text = text;
            this.sources = sources;
            this.cssClassForHighlight = cssClassForHighlight;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Search2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search2Response", Namespace="http://www.gxtechnical.com/", Order=0)]
        public GX26Bot.ServiceReference.Search2ResponseBody Body;
        
        public Search2Response() {
        }
        
        public Search2Response(GX26Bot.ServiceReference.Search2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gxtechnical.com/")]
    public partial class Search2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GX26Bot.ServiceReference.SearchResult Search2Result;
        
        public Search2ResponseBody() {
        }
        
        public Search2ResponseBody(GX26Bot.ServiceReference.SearchResult Search2Result) {
            this.Search2Result = Search2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Search3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search3", Namespace="http://www.gxtechnical.com/", Order=0)]
        public GX26Bot.ServiceReference.Search3RequestBody Body;
        
        public Search3Request() {
        }
        
        public Search3Request(GX26Bot.ServiceReference.Search3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gxtechnical.com/")]
    public partial class Search3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GX26Bot.ServiceReference.SearchParameter searchParameter;
        
        public Search3RequestBody() {
        }
        
        public Search3RequestBody(GX26Bot.ServiceReference.SearchParameter searchParameter) {
            this.searchParameter = searchParameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Search3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search3Response", Namespace="http://www.gxtechnical.com/", Order=0)]
        public GX26Bot.ServiceReference.Search3ResponseBody Body;
        
        public Search3Response() {
        }
        
        public Search3Response(GX26Bot.ServiceReference.Search3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gxtechnical.com/")]
    public partial class Search3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GX26Bot.ServiceReference.SearchResult Search3Result;
        
        public Search3ResponseBody() {
        }
        
        public Search3ResponseBody(GX26Bot.ServiceReference.SearchResult Search3Result) {
            this.Search3Result = Search3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchPrivateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchPrivate", Namespace="http://www.gxtechnical.com/", Order=0)]
        public GX26Bot.ServiceReference.SearchPrivateRequestBody Body;
        
        public SearchPrivateRequest() {
        }
        
        public SearchPrivateRequest(GX26Bot.ServiceReference.SearchPrivateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gxtechnical.com/")]
    public partial class SearchPrivateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GX26Bot.ServiceReference.SourceParam[] sources;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cssClassForHighlight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string passwordPrivateSearch;
        
        public SearchPrivateRequestBody() {
        }
        
        public SearchPrivateRequestBody(string text, GX26Bot.ServiceReference.SourceParam[] sources, string cssClassForHighlight, int pageNumber, int pageSize, string passwordPrivateSearch) {
            this.text = text;
            this.sources = sources;
            this.cssClassForHighlight = cssClassForHighlight;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
            this.passwordPrivateSearch = passwordPrivateSearch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchPrivateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchPrivateResponse", Namespace="http://www.gxtechnical.com/", Order=0)]
        public GX26Bot.ServiceReference.SearchPrivateResponseBody Body;
        
        public SearchPrivateResponse() {
        }
        
        public SearchPrivateResponse(GX26Bot.ServiceReference.SearchPrivateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gxtechnical.com/")]
    public partial class SearchPrivateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GX26Bot.ServiceReference.SearchResult SearchPrivateResult;
        
        public SearchPrivateResponseBody() {
        }
        
        public SearchPrivateResponseBody(GX26Bot.ServiceReference.SearchResult SearchPrivateResult) {
            this.SearchPrivateResult = SearchPrivateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchServiceSoapChannel : GX26Bot.ServiceReference.SearchServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceSoapClient : System.ServiceModel.ClientBase<GX26Bot.ServiceReference.SearchServiceSoap>, GX26Bot.ServiceReference.SearchServiceSoap {
        
        public SearchServiceSoapClient() {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GX26Bot.ServiceReference.SearchResponse GX26Bot.ServiceReference.SearchServiceSoap.Search(GX26Bot.ServiceReference.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public GX26Bot.ServiceReference.Document[] Search(string text, GX26Bot.ServiceReference.SourceParam[] sources, string cssClassForHighlight) {
            GX26Bot.ServiceReference.SearchRequest inValue = new GX26Bot.ServiceReference.SearchRequest();
            inValue.Body = new GX26Bot.ServiceReference.SearchRequestBody();
            inValue.Body.text = text;
            inValue.Body.sources = sources;
            inValue.Body.cssClassForHighlight = cssClassForHighlight;
            GX26Bot.ServiceReference.SearchResponse retVal = ((GX26Bot.ServiceReference.SearchServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GX26Bot.ServiceReference.SearchResponse> GX26Bot.ServiceReference.SearchServiceSoap.SearchAsync(GX26Bot.ServiceReference.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<GX26Bot.ServiceReference.SearchResponse> SearchAsync(string text, GX26Bot.ServiceReference.SourceParam[] sources, string cssClassForHighlight) {
            GX26Bot.ServiceReference.SearchRequest inValue = new GX26Bot.ServiceReference.SearchRequest();
            inValue.Body = new GX26Bot.ServiceReference.SearchRequestBody();
            inValue.Body.text = text;
            inValue.Body.sources = sources;
            inValue.Body.cssClassForHighlight = cssClassForHighlight;
            return ((GX26Bot.ServiceReference.SearchServiceSoap)(this)).SearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GX26Bot.ServiceReference.Search2Response GX26Bot.ServiceReference.SearchServiceSoap.Search2(GX26Bot.ServiceReference.Search2Request request) {
            return base.Channel.Search2(request);
        }
        
        public GX26Bot.ServiceReference.SearchResult Search2(string text, GX26Bot.ServiceReference.SourceParam[] sources, string cssClassForHighlight, int pageNumber, int pageSize) {
            GX26Bot.ServiceReference.Search2Request inValue = new GX26Bot.ServiceReference.Search2Request();
            inValue.Body = new GX26Bot.ServiceReference.Search2RequestBody();
            inValue.Body.text = text;
            inValue.Body.sources = sources;
            inValue.Body.cssClassForHighlight = cssClassForHighlight;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            GX26Bot.ServiceReference.Search2Response retVal = ((GX26Bot.ServiceReference.SearchServiceSoap)(this)).Search2(inValue);
            return retVal.Body.Search2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GX26Bot.ServiceReference.Search2Response> GX26Bot.ServiceReference.SearchServiceSoap.Search2Async(GX26Bot.ServiceReference.Search2Request request) {
            return base.Channel.Search2Async(request);
        }
        
        public System.Threading.Tasks.Task<GX26Bot.ServiceReference.Search2Response> Search2Async(string text, GX26Bot.ServiceReference.SourceParam[] sources, string cssClassForHighlight, int pageNumber, int pageSize) {
            GX26Bot.ServiceReference.Search2Request inValue = new GX26Bot.ServiceReference.Search2Request();
            inValue.Body = new GX26Bot.ServiceReference.Search2RequestBody();
            inValue.Body.text = text;
            inValue.Body.sources = sources;
            inValue.Body.cssClassForHighlight = cssClassForHighlight;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            return ((GX26Bot.ServiceReference.SearchServiceSoap)(this)).Search2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GX26Bot.ServiceReference.Search3Response GX26Bot.ServiceReference.SearchServiceSoap.Search3(GX26Bot.ServiceReference.Search3Request request) {
            return base.Channel.Search3(request);
        }
        
        public GX26Bot.ServiceReference.SearchResult Search3(GX26Bot.ServiceReference.SearchParameter searchParameter) {
            GX26Bot.ServiceReference.Search3Request inValue = new GX26Bot.ServiceReference.Search3Request();
            inValue.Body = new GX26Bot.ServiceReference.Search3RequestBody();
            inValue.Body.searchParameter = searchParameter;
            GX26Bot.ServiceReference.Search3Response retVal = ((GX26Bot.ServiceReference.SearchServiceSoap)(this)).Search3(inValue);
            return retVal.Body.Search3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GX26Bot.ServiceReference.Search3Response> GX26Bot.ServiceReference.SearchServiceSoap.Search3Async(GX26Bot.ServiceReference.Search3Request request) {
            return base.Channel.Search3Async(request);
        }
        
        public System.Threading.Tasks.Task<GX26Bot.ServiceReference.Search3Response> Search3Async(GX26Bot.ServiceReference.SearchParameter searchParameter) {
            GX26Bot.ServiceReference.Search3Request inValue = new GX26Bot.ServiceReference.Search3Request();
            inValue.Body = new GX26Bot.ServiceReference.Search3RequestBody();
            inValue.Body.searchParameter = searchParameter;
            return ((GX26Bot.ServiceReference.SearchServiceSoap)(this)).Search3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GX26Bot.ServiceReference.SearchPrivateResponse GX26Bot.ServiceReference.SearchServiceSoap.SearchPrivate(GX26Bot.ServiceReference.SearchPrivateRequest request) {
            return base.Channel.SearchPrivate(request);
        }
        
        public GX26Bot.ServiceReference.SearchResult SearchPrivate(string text, GX26Bot.ServiceReference.SourceParam[] sources, string cssClassForHighlight, int pageNumber, int pageSize, string passwordPrivateSearch) {
            GX26Bot.ServiceReference.SearchPrivateRequest inValue = new GX26Bot.ServiceReference.SearchPrivateRequest();
            inValue.Body = new GX26Bot.ServiceReference.SearchPrivateRequestBody();
            inValue.Body.text = text;
            inValue.Body.sources = sources;
            inValue.Body.cssClassForHighlight = cssClassForHighlight;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            inValue.Body.passwordPrivateSearch = passwordPrivateSearch;
            GX26Bot.ServiceReference.SearchPrivateResponse retVal = ((GX26Bot.ServiceReference.SearchServiceSoap)(this)).SearchPrivate(inValue);
            return retVal.Body.SearchPrivateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GX26Bot.ServiceReference.SearchPrivateResponse> GX26Bot.ServiceReference.SearchServiceSoap.SearchPrivateAsync(GX26Bot.ServiceReference.SearchPrivateRequest request) {
            return base.Channel.SearchPrivateAsync(request);
        }
        
        public System.Threading.Tasks.Task<GX26Bot.ServiceReference.SearchPrivateResponse> SearchPrivateAsync(string text, GX26Bot.ServiceReference.SourceParam[] sources, string cssClassForHighlight, int pageNumber, int pageSize, string passwordPrivateSearch) {
            GX26Bot.ServiceReference.SearchPrivateRequest inValue = new GX26Bot.ServiceReference.SearchPrivateRequest();
            inValue.Body = new GX26Bot.ServiceReference.SearchPrivateRequestBody();
            inValue.Body.text = text;
            inValue.Body.sources = sources;
            inValue.Body.cssClassForHighlight = cssClassForHighlight;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            inValue.Body.passwordPrivateSearch = passwordPrivateSearch;
            return ((GX26Bot.ServiceReference.SearchServiceSoap)(this)).SearchPrivateAsync(inValue);
        }
    }
}
